#!/bin/zsh
command=${1}
ps | grep -Ee "([0-9]{1,5})\ ttys[0-9]{0,3}\ {0,3}[0-9]{1,2}\:[0-9]{1,2}\.[0-9]{1,2}\ .*${command}" | sed -Ee 's/([0-9]{1,5})\ ttys[0-9]{3}\ {0,3}[0-9]{1,2}\:[0-9]{1,2}\.[0-9]{1,2}\ [[:print:]]+/\1/' | read processPID;
echo "PID ${processPID}"
